### PR TITLE
replace splash icon

### PR DESCRIPTION
**Pull request by mattfred**
@ryancarlson I forgot to change the message on my commit. Sorry.

### CODE REVIEW

**Comment by ryancarlson** [comment]
looks good.  have you tested it on the Nexus phone and your Samsung?

**Comment by mattfred** [comment]
Yes. I have also included it in the main layout update. So this will be deployed along with that.

**Comment by ryancarlson** [comment]
Great.  So this PR can be closed then and we'll just merge the layouts branch?

**Comment by mattfred** [comment]
Correct :-)

**Comment by ryancarlson** [comment]
:+1: nice job.

**Comment by mattfred** [comment]
Thanks

**Pull request closed without merging**
