### PR TITLE
Manage notifications

### PR DESCRIPTION
**Pull request by mattfred**

### CODE REVIEW

**Comment by mattfred** [comment]
@ryancarlson Here is the notification update you asked for. I put it on my phone about an hour and a half ago, and I have not gotten any notifications yet. I believe the API sends out notifications every hour, so I should have gotten one by now. Anyways, all this to say that it seems to be working. :-)

**Comment by ryancarlson** [comment]
Sweet, i'll take a look!

**Comment by ryancarlson** [comment]
Code looks great.  This is probably the best you've done at breaking things up into individual commits!  It makes it so much easier to review this way.  Let me some testing on the Nexus phone and get back to you when it can be merged

**Comment by mattfred** [comment]
Great. Thanks

**Comment by mattfred** [comment]
I am closing this since it is now part of the new layout PR.

**Pull request closed without merging**
